### ISSUE TITLE
Repeated Command Bugs

### ISSUE THREAD

**Issue by tararoys** [chaosparrot/talon_hud#11]
If a walk through step has the same command repeated multiple times, it will highlight all the repeats the first time you say them.  
Saying other commands will highlight them.  
When all of the commands are highlighted, it will not do the default behavior of automatically going to the next step.  

Example step attatched.  

[same_command_bug(walkthrough).md](https://github.com/chaosparrot/talon_hud/files/7899335/same_command_bug.walkthrough.md)
.

**Comment by chaosparrot** [comment]
Fixed in v0.6!
