### ISSUE TITLE
Have 'skip step' command automatically appended to walkthrough steps that do not have any commands in them

### ISSUE THREAD

**Issue by tararoys** [chaosparrot/talon_hud#12]
I have several informational-only walkthrough steps that don't include voice commands.  It would be nice if the skip step command were automatically appended to such walkthrough commands.  It would also be nice if the command were aliased to 'next step' since, in this context, 'next step; would imply going to the next step and 'skip step' would imply skipping the next step.  

This is what it currently looks like:  
![image](https://user-images.githubusercontent.com/1163925/150186900-39eaad94-6c40-409f-8653-3c6e9253fc96.png)

This is what I would like it to look like: 
![image](https://user-images.githubusercontent.com/1163925/150187195-e374c675-bbdb-4257-8c2a-f384fa1427a7.png)

This would reduce mental load on walkthrough users who don't have to remember the skip command or the 'walkthough options' commands.

**Comment by chaosparrot** [comment]
Fixed in v0.6 by adding the footer buttons
