### ISSUE TITLE
 option number command does not work when accessing walk through options menu using the command to Walk through

### ISSUE THREAD

**Issue by tararoys** [chaosparrot/talon_hud#15]
1. I say the command toolkit walk through.  The walk through options menu appears.
2. neither saying 'option one' or 'head up display' does anything. instead, talon continues typing into whatever textbox was focused last.

 however, when I accessed the toolkit walked through menu through the toolkit options menu, the voice commands for the walk through options menu work.

**Comment by chaosparrot** [comment]
I have noticed weird behavior with the choice widgets myself ( same thing seems to happen on the context menu as well ). I'll look into it!

**Comment by chaosparrot** [comment]
Fixed in v0.6!
