### ISSUE TITLE
Status bar configurations via settings 

### ISSUE THREAD

**Issue by Nova38** [chaosparrot/talon_hud#18]
First of thanks for the work you have put into this amazing project. 

I was wondering if it would be possible to support the activation of the various status bar components via a setting instead of uncommenting a few lines? 

```You can add the current natural language by uncommenting line 96 from the display.py fileYou can add the microphone toggle by uncommenting line 100 from the display.py file```

**Comment by chaosparrot** [comment]
You will be pleased to know that I've done some pretty heavy tinkering on that front lately, I'm planning on having a release for this thing sometime next week ( depending on whether or not I want complete documentation for it or not ). In that new version you will be able to have your status bar settings stick in between talon restarts.

I'll close this issue once that release is finalized and put on master.

**Comment by Nova38** [comment]
Fantastic to hear! Thanks you

**Comment by chaosparrot** [comment]
The release has been made, you should now be able to enjoy not having to tweak the code :)
