### ISSUE TITLE
If a command phrase contains a walthrough command, a walkthrough step will highlight it even if the phrase is part of a larger completely different command.

### ISSUE THREAD

**Issue by tararoys** [chaosparrot/talon_hud#19]
walktrhough Bug :

1. when I was using cursorless in vscode, I said the phrase 'take look' to highlight a word.  
2.  The walkthrough step I happened to have open had 'look' as a separate command. 
3.  In the walkthrough, 'look' was highlighted green, even though I was saying the command 'take look' and not 'look'

This was in one of my markdown tutorlas, specifically on this step: 

```
The Talon phonetic alphabet allows you to spell quickly and accurately.  Let's spell the word Talon. Speaking as quickly or as slowly as you want, try saying the command phrase `trap` `air` `look` `odd` `near` into a text area.
```

![image](https://user-images.githubusercontent.com/1163925/158820573-2e54775f-75c4-47dd-b22d-5596dcb0b8a0.png)

**Comment by chaosparrot** [comment]
Thanks for the feedback!

Unfortunately, I cannot check where one part of a command ends, and another starts, in a single phrase. For instance, if someone would say `trap made air look` I would still want to make trap, air and look trigger, and not just trap. And especially for letters, which tend to be used in a lot of different commands like in cursorless or other configurations.

Would it be fine if I added ordering of the commands by default? Meaning: Trap air urge look would still trigger trap air and look, but urge look air trap would only trigger trap in the walkthrough step?

**Comment by tararoys** [comment]
i think command ordering is a sensible default, since the whole point of a
walkthrough step.  It would eliminate the vast majority of accidental
highlights, too.  I haven't checked recently if having the same command
twice in the same step
still highlights both commands, but command ordering would fix that problem
too.

**Comment by chaosparrot** [comment]
Okay, I will make the command ordering chronological by default. That will be the last walkthrough change that I will make before I release the next version of the HUD which contains the improved walkthrough flow and widget.

**Comment by chaosparrot** [comment]
This has been added in the v0.6 release :) thanks!
