### ISSUE TITLE
Cursor tracker add/remove doesn't trigger refresh

### ISSUE THREAD

**Issue by wolfmanstout** [chaosparrot/talon_hud#21]
I use hud_publish_screen_regions and hud_clear_screen_regions to add and remove a cursor tracker, but the display does not update until I wiggle the cursor.

**Comment by chaosparrot** [comment]
Noticed this as well when I tried out some cursor stuff, will try to fix

**Comment by chaosparrot** [comment]
Been a long time coming, but I fixed this issue now :) Sorry for the long wait, wasn't working on the master branch in a while

**Comment by wolfmanstout** [comment]
Fantastic, thank you for fixing this! I was hanging out on an old detached commit for the last few months :-)
