### ISSUE TITLE
Tutorial shows commands that don't work

### ISSUE THREAD

**Issue by douglasg14b** [chaosparrot/talon_hud#22]
Example:

![image](https://user-images.githubusercontent.com/1400380/160907571-628c140f-dedc-4efe-a33b-ec7eb02bba55.png)

`widget settings next` doesn't work. The actual relevant command should be shown here.

**Comment by douglasg14b** [comment]
This also is not interactable via mouse (Mouse just clicks behind it), so I have no way to close it or move it...

**Comment by chaosparrot** [comment]
I will try to replicate it, thanks for the feedback :)
