### ISSUE TITLE
Cannot interact with some GUI elements with a mouse

### ISSUE THREAD

**Issue by douglasg14b** [chaosparrot/talon_hud#23]
In an attempt to solve for crashing issues I am using `backend="software"` for all Canvas calls per Aegis instruction.

After doing this some elements are not intractable, such as the ones below. Mouse clicks go straight through them.

**No mouse Interaction:**

![image](https://user-images.githubusercontent.com/1400380/160913159-82e5df43-f299-449c-9026-44259fa2e99a.png)

![image](https://user-images.githubusercontent.com/1400380/160913112-e1f7c731-7d2e-4315-8dd1-93b1fd71d4c0.png)

![image](https://user-images.githubusercontent.com/1400380/160913315-76ddce0f-06f8-4743-ac42-2dcc461d545d.png)

**Comment by chaosparrot** [comment]
I will try it out with  background="software" to see if I can replicate it.

As far as the `widget settings next` block, that isn't actually a button that receives clicks, it is intended to work like that.

**Comment by chaosparrot** [comment]
I fixed this in master - To see if this fixes it for you, update to the latest HUD and go to the base_widget.py file, and then uncomment line 449 with the #"backend": "software" on it. Thats the way it works for me, I can click on the status bar and on text panels without a problem now.
