### ISSUE TITLE
Feature request: way to quickly show/hide all overlays without animation

### ISSUE THREAD

**Issue by wolfmanstout** [chaosparrot/talon_hud#28]
I'd like to have a way to quickly hide all the overlays while I take a screenshot and then restore them. I tried doing this in display.py by iterating through all the widgets in HeadUpDisplay.widget_manager and calling canvas.hide/show, but it turns out there are other overlays that are unaffected (e.g. the ones activated via hud_publish_screen_regions).

Is this an action you could add, or give me a pointer to how I might implement this for all the overlays?

**Comment by chaosparrot** [comment]
I kind of liked watermarking peoples screenshots with the HUD, but I get why you would want to disable it temporarily.

I added an action to display.py ( hud_set_visibility ) where you can hide or show all the canvases without it affecting enabled statuses, the content flow or anything, as regular hiding actually removes the canvases entirely.

I also added a short time delay in it, to make sure that you can use it in a talon file and be sure the screen is clear after the action finishes, I've tested this with this talon command:

```talon
screenshot this:
    user.hud_set_visibility(0)
    key(printscr)
    user.hud_set_visibility(1)
```

And confirmed the screenshot was clean of HUD elements.

I didn't add a default voice command for it, as I figured it would be hard to explain the distinction between 'hidden' and 'invisible' without majorly confusing users.

**Comment by wolfmanstout** [comment]
Awesome, thank you! 

I like the idea of watermarking but my use case of OCR really benefits from a clean screenshot. In case you are curious: https://github.com/wolfmanstout/talon-gaze-ocr

**Comment by wolfmanstout** [comment]
Would you be open to adding an optional parameter `pause_seconds=0.05` to the new action to specify sleep? 100 ms total is a visible hit on my most frequently used commands, and experimentally I found that 0.01 pause was enough on both of my (fast) computers (Windows and Mac).

Thank you for implementing this so quickly, it works really well!

**Comment by chaosparrot** [comment]
I added the suggestion for pause_seconds to the latest master commit, so you should be able to set it now :)

**Comment by wolfmanstout** [comment]
Talon Beta now makes it possible to have any canvas hidden from the capture API, without having to visibly hide it. That would be a better solution here because there is no need to wait for it to be hidden, and it wouldn't cause any UI flicker. The following very short commit worked for me in Talon Beta (it also doesn't break Talon Public):
https://github.com/chaosparrot/talon_hud/commit/45663686d8735a237952d574c488df12efd47b91

I'm guessing there are both use cases where it is helpful to show the HUD and to hide it. Would you be interested in adding a Talon setting which controls whether the HUD is visible within screenshots? I can send a PR for this if you'd like.

**Comment by chaosparrot** [comment]
Ooh, that sounds like a great feature to have! I'd be interested in having a setting for that. Making a PR for it would be nice, I won't be able to work on OSS stuff until the weekend.

> Talon Beta now makes it possible to have any canvas hidden from the capture API, without having to visibly hide it. That would be a better solution here because there is no need to wait for it to be hidden, and it wouldn't cause any UI flicker. The following very short commit worked for me in Talon Beta (it also doesn't break Talon Public): [4566368](https://github.com/chaosparrot/talon_hud/commit/45663686d8735a237952d574c488df12efd47b91)
> 
> I'm guessing there are both use cases where it is helpful to show the HUD and to hide it in screenshots. Would you be interested in adding a Talon setting which controls whether the HUD is visible within screenshots? I can send a PR for this if you'd like.

Ooh, that sounds like a great feature to have! I'd be interested in having a setting for that. Making a PR for it would be nice, I won't be able to work on OSS stuff until the weekend.
